# Use root/example as user/password credentials

version: '3'
services:
  database:
    image: mongo:4.4
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootSHBsa
      - MONGO_INITDB_ROOT_PASSWORD=1dFDiwes
      - MONGO_INITDB_DATABASE=user_arbitrage
      - MONGO_INITDB_USERNAME=oIuern
      - MONGO_INITDB_PASSWORD=POfd54
    volumes:
      - ./init/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./database:/data/db
    ports:
      - 27018:27017
